"""empty message

Revision ID: 3b1cf884b92e
Revises: 917738df468e
Create Date: 2026-09-03 12:30:34.493077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b1cf884b92e'
down_revision: Union[str, Sequence[str], None] = '917738df468e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_centers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_centers_identifier'), 'work_centers', ['identifier'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unique_code', sa.String(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('is_aggregated', sa.Boolean(), nullable=False),
    sa.Column('aggregated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_product_batch_aggregated', 'products', ['batch_id', 'is_aggregated'], unique=False)
    op.create_index(op.f('ix_products_is_aggregated'), 'products', ['is_aggregated'], unique=False)
    op.create_index(op.f('ix_products_unique_code'), 'products', ['unique_code'], unique=True)
    op.add_column('batches', sa.Column('work_center_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'batches', 'work_centers', ['work_center_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'batches', type_='foreignkey')
    op.drop_column('batches', 'work_center_id')
    op.drop_index(op.f('ix_products_unique_code'), table_name='products')
    op.drop_index(op.f('ix_products_is_aggregated'), table_name='products')
    op.drop_index('idx_product_batch_aggregated', table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_work_centers_identifier'), table_name='work_centers')
    op.drop_table('work_centers')
    # ### end Alembic commands ###
