"""empty message

Revision ID: 5213c6a827b6
Revises: b36f23b9bcd9
Create Date: 2026-09-10 11:43:26.386987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5213c6a827b6'
down_revision: Union[str, Sequence[str], None] = 'b36f23b9bcd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webhook_subscriptions', 'secret_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook_subscriptions', sa.Column('secret_key', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
