"""empty message

Revision ID: 72b5a0145876
Revises: bd7be39d452f
Create Date: 2026-10-05 16:01:38.240982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72b5a0145876'
down_revision: Union[str, Sequence[str], None] = 'bd7be39d452f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('webhook_deliveries_subscription_id_fkey'), 'webhook_deliveries', type_='foreignkey')
    op.create_foreign_key(None, 'webhook_deliveries', 'webhook_subscriptions', ['subscription_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'webhook_deliveries', type_='foreignkey')
    op.create_foreign_key(op.f('webhook_deliveries_subscription_id_fkey'), 'webhook_deliveries', 'webhook_subscriptions', ['subscription_id'], ['id'])
    # ### end Alembic commands ###
