"""empty message

Revision ID: 7d2355cd39be
Revises: 98ef8c56ab66
Create Date: 2026-10-01 11:19:12.380724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d2355cd39be'
down_revision: Union[str, Sequence[str], None] = '98ef8c56ab66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook_subscriptions', sa.Column('secret_key', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webhook_subscriptions', 'secret_key')
    # ### end Alembic commands ###
